apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "migrationpilot.fullname" . }}-config
  labels:
    {{- include "migrationpilot.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.environment | quote }}
