apiVersion: v1
kind: Service
metadata:
  name: {{ include "migrationpilot.fullname" . }}-api
  labels:
    {{- include "migrationpilot.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "migrationpilot.api.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "migrationpilot.fullname" . }}-web
  labels:
    {{- include "migrationpilot.web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "migrationpilot.web.selectorLabels" . | nindent 4 }}
